### ISSUE TITLE
Difficulty in classification

### ISSUE THREAD

**Issue by vegetable-lion** [Darkbblue/diffusion-feature#2]
Hi, thanks for your brilliant work! I'm currently working on some classification tasks and have encountered a challenge. The feature output from the mid block of UNet  is of shape (1, 1024, 32, 32), which has a large number of channels. Could you please provide guidance on how to set up the downstream model for this classification task?

**Comment by Darkbblue** [comment]
> Hi, thanks for your brilliant work! I'm currently working on some classification tasks and have encountered a challenge. The feature output from the mid block of UNet is of shape (1, 1024, 32, 32), which has a large number of channels. Could you please provide guidance on how to set up the downstream model for this classification task?

In fact I don't recommend using diffusion features for image-level tasks. But if you insist, consider using a ResNet that keeps the same number of dimensions throughout the entire network. In addition, such huge features make it hard to load the features of all images into memory at once. You can choose to load them batch by batch.

**Comment by vegetable-lion** [comment]
> Thank you so much and I will try!
